runtime: python311
entrypoint: gunicorn -k uvicorn.workers.UvicornWorker -b :$PORT main:app

instance_class: F1  # gratuita
automatic_scaling:
  max_instances: 1
  min_idle_instances: 0
  max_idle_instances: 0
