name: Deploy para App Engine

on:
  push:
    branches:
      - main
    paths:
      - 'tc-backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: tc-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: tc-backend
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/tc-backend
          region: us-central1